name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run Jest
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_URI_TEST_DB: ${{ secrets.MONGODB_URI_TEST_DB }}
          MONGODB_URI_PROD: ${{ secrets.MONGODB_URI_PROD }}
          MONGODB_URI_PROD_TEST_DB: ${{ secrets.MONGODB_URI_PROD_TEST_DB }}
          OPEN_AI_API_SECRET_KEY: ${{ secrets.OPEN_AI_API_SECRET_KEY }}
          GEMINI_AI_API_SECRET_KEY: ${{ secrets.GEMINI_AI_API_SECRET_KEY }}
          USE_OPEN_AI: ${{ secrets.USE_OPEN_AI }}
          AMPLITUDE_SEND_ANALYTICS_URL: ${{ secrets.AMPLITUDE_SEND_ANALYTICS_URL }}
          AMPLITUDE_DELETE_ANALYTICS_URL: ${{ secrets.AMPLITUDE_DELETE_ANALYTICS_URL }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          AMPLITUDE_SECRET_KEY: ${{ secrets.AMPLITUDE_SECRET_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ACCESS_EXPIRATION_MINUTES: ${{ secrets.JWT_ACCESS_EXPIRATION_MINUTES }}
          JWT_REFRESH_EXPIRATION_DAYS: ${{ secrets.JWT_REFRESH_EXPIRATION_DAYS }}
          JWT_RESET_PASSWORD_EXPIRATION_MINUTES: ${{ secrets.JWT_RESET_PASSWORD_EXPIRATION_MINUTES }}
          JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: ${{ secrets.JWT_VERIFY_EMAIL_EXPIRATION_MINUTES }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        run: npm test